wcconsultancy/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from main import views as main_views

urlpatterns = [
    url(r'^university/$',
        main_views.UniversityTemplateView.as_view(),
        name='universities'
    ),
    url(r'^university/(?P<id>\d+)/$',
        main_views.UniversityDetailTemplateView.as_view(),
        name='university-detail'
    ),
    url(r'^about/$',
        main_views.AboutTemplateView.as_view(),
        name='about'
    ),
    url(r'^pizzapasta/',
        admin.site.urls
    ),
    url(r'^$',
        main_views.HomeTemplateView.as_view(),
        name='index'
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/models/admission.py
from __future__ import unicode_literals

from django.db import models

from main.models.university import University

PROGRAM_TYPE = (
    (0, 'Undergraduate'),
    (1, 'Graduate')
)

ADMISSION_TYPE = (
    (0, 'Freshman'),
    (1, 'Transfer')
)

class Admission(models.Model):
    program_type = models.IntegerField(default=0, choices=PROGRAM_TYPE)
    admission_type = models.IntegerField(default=0, choices=ADMISSION_TYPE)
    detail = models.TextField(blank=True, null=True)
    university = models.ForeignKey(University, related_name='admission')

    def __unicode__(self):
        return '{}:{} {}'.format(self.university.name,
                                 PROGRAM_TYPE[self.program_type][1],
                                 ADMISSION_TYPE[self.admission_type]
                                                [1])


class Requirement(models.Model):
    detail = models.TextField()
    admission = models.ForeignKey(Admission, related_name='requirements')

    def __unicode__(self):
        return '{}:{} {}'.format(self.admission.university.name,
                                PROGRAM_TYPE[self.admission.program_type][1],
                                ADMISSION_TYPE[self.admission.admission_type]
                                                [1])

main/models/scholarship.py
from __future__ import unicode_literals

from django.db import models

from main.models.university import University


class Scholarship(models.Model):
    detail = models.TextField(blank=True, null=True)
    additional_detail = models.TextField(blank=True, null=True)
    university = models.ForeignKey(University, related_name='scholarship')


class Eligibility(models.Model):
    """
    This model is used for each eligibility item specified when applying
    for a scholarship
    """
    detail = models.TextField(blank=True, null=True)
    scholarship = models.ForeignKey(Scholarship, related_name='eligibility')

main/models/state.py
from __future__ import unicode_literals

from django.db import models

class State(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

main/models/tuition.py
from __future__ import unicode_literals

from django.db import models

from main.models.university import University


class Tuition(models.Model):
    detail = models.TextField(blank=True, null=True)
    additional_detail = models.TextField(blank=True, null=True)
    university = models.ForeignKey(University, related_name='tuition')


class Fee(models.Model):
    """
    This model is used for each fee item specified on each
    university
    """
    name = models.CharField(max_length=255)
    amount = models.FloatField()
    detail = models.TextField(blank=True, null=True)
    tuition = models.ForeignKey(Tuition, related_name='fee')

main/models/university.py
from __future__ import unicode_literals

from django.db import models
from main.models.state import State

# Create your models here.

class University(models.Model):
    name = models.CharField(max_length=255)
    background = models.TextField(blank=True, null=True)
    state = models.ForeignKey(State)
    acceptance_rate = models.FloatField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    logo = models.ImageField(upload_to='img/logos', blank=True, null=True)
    logo_link = models.CharField(max_length=512, blank=True, null=True)

    def __unicode__(self):
        return self.name

class TotalStudents(models.Model):
    total_number = models.IntegerField()
    year = models.CharField(max_length=4)
    university = models.ForeignKey(University, related_name='total_students')
    is_international = models.BooleanField(default=False)

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeTemplateView(TemplateView):
    template_name = 'home/index.html'

main/views/about.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class AboutTemplateView(TemplateView):
    template_name = 'about/about.html'

main/views/home.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeTemplateView(TemplateView):
    template_name = 'home/index.html'

main/views/university.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from main.models import (University, Admission, Requirement)

UNIVERSITIES_PER_PAGE = 6


class UniversityTemplateView(TemplateView):
    template_name = 'universities/university_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(UniversityTemplateView, self).get_context_data(
                        *args, **kwargs)
        universities = University.objects.all().order_by('name')
        paginator = Paginator(universities, UNIVERSITIES_PER_PAGE)
        page = self.request.GET.get('page')
        try:
            univs = paginator.page(page)
        except PageNotAnInteger:
            univs = paginator.page(1)
        except EmptyPage:
            univs = paginator.page(paginator.num_pages)
        context['universities'] = univs
        return context


class UniversityDetailTemplateView(TemplateView):
    template_name = 'universities/university_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(UniversityDetailTemplateView, self).get_context_data(
                        *args, **kwargs)
        university = get_object_or_404(University, **kwargs)
        admissions = Admission.objects.filter(university=university)
        context['admissions'] = admissions
        context['university'] = university
        return context

main/templates/about/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="container">
        <br />
        <div class="row">
            <div class="slider">
                <ul class="slides">
                    <li>
                        <img class="darken-img" src="{% static 'main/img/rsz_carousel1.jpg' %}">
                        <div class="caption center-align">
                            <h3>What is W&amp;C?</h3>
                            <h5 class="light grey-text text-lighten-3">
                                W&amp;C is an international
                                education service provider that helps students
                                from emerging economies to obtain world-class education in the United States
                            </h5>
                        </div>
                    </li>
                    <li>
                        <img class="darken-img" src="{% static 'main/img/rsz_carousel2.jpg' %}">
                        <div class="caption center-align">
                            <h3>What do we do?</h3>
                            <h4>Provide <strong><i>SMART</i></strong> Information</h4>
                            <h5 class="light grey-text text-lighten-3">
                                Our database was designed to provide students the access to smart information
                                connecting them to over 100 colleges and universities in the United States.
                            </h5>
                        </div>
                    </li>
                    <li>
                        <img class="darken-img" src="{% static 'main/img/rsz_carousel3.jpg' %}">
                        <div class="caption center-align">
                            <h3>Evaluation &amp; Guidance</h3>
                            <h5 class="light grey-text text-lighten-3">
                                Our team evaluates and guides students in the application process.
                            </h5>
                        </div>
                    </li>
                    <li>
                        <img class="darken-img" src="{% static 'main/img/rsz_carousel4.jpg' %}">
                        <div class="caption center-align">
                            <h3>Information Driven</h3>
                            <h5 class="light grey-text text-lighten-3">
                                We collect only the most pivotal information that are directly derived from
                                school administrators, program directors or admission officers.
                            </h5>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col s5">
                <div class="card-panel blue">
                    <h5 class="white-text">About Us</h5>
                    <div style="text-align: justify">
                        <span class="white-text">
                            W&amp;C was developed by a group of international scholars who are passionate
                            and committed to helping students achieve higher education.
                            Our experience drives us to inspire talented individuals to conquer the world of
                            bright ideas. Studying in the United States has tremendous opportunities and we want
                            our clients to experience them. However, as international students ourselves we
                            understand every obstacle international students face before, during and after the admission process.
                            W&amp;C was created to help students in emerging economies to fulfill their own dreams.
                        </span>
                    </div>
                </div>
            </div>
            <div class="col s7">
                <div class="row" style="margin-bottom: 1px">
                    <div class="center">
                        <h4 class="wc-color" style="margin-bottom: 1px">The Team</h4>
                    </div>
                </div>
                <div class="row" style="margin-bottom: 1px">
                    <div class="center">
                        <span class="wc-color light">(click photo for bio)</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col s1" style="margin-left: 27px"></div>
                    <a href="#modal1">
                        <div class="col s3">
                            <img class="circle responsive-img" src="{% static 'main/img/zhang.png' %}">
                            <div class="center"><span>Zhang</span></div>
                            <div class="center"><span class="center light">Co-Founder</span></div>
                        </div>
                    </a>
                    <a href="#modal2">
                        <div class="col s3">
                            <img class="circle responsive-img" src="{% static 'main/img/zhang.png' %}">
                            <div class="center"><span>Zhang</span></div>
                            <div class="center"><span class="center light">Co-Founder</span></div>
                        </div>
                    </a>
                    <a href="#modal3">
                        <div class="col s3">
                            <img class="circle responsive-img" src="{% static 'main/img/zhang.png' %}">
                            <div class="center"><span>Zhang</span></div>
                            <div class="center"><span class="center light">Co-Founder</span></div>
                        </div>
                    </a>
                </div>
                <div class="row">
                    <div class="col s3" style="margin-left: 10px"></div>
                    <a href="#modal4">
                    <div class="col s3">
                        <img class="circle responsive-img" src="{% static 'main/img/zhang.png' %}">
                        <div class="center"><span>Zhang</span></div>
                        <div class="center"><span class="center light">Co-Founder</span></div>
                    </div>
                    </a>
                    <a href="#modal5">
                        <div class="col s3">
                            <img class="circle responsive-img" src="{% static 'main/img/zhang.png' %}">
                            <div class="center"><span>Zhang</span></div>
                            <div class="center"><span class="center light">Co-Founder</span></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <!-- Modal Structure -->
        <div id="modal1" class="modal">
            <div class="modal-content">
                <h4>Name Here</h4>
                <p>{% lorem %}</p>
            </div>
            <div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
        <div id="modal2" class="modal">
            <div class="modal-content">
                <h4>Name Here</h4>
                <p>{% lorem %}</p>
            </div>
            <div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
        <div id="modal3" class="modal">
            <div class="modal-content">
                <h4>Name Here</h4>
                <p>{% lorem %}</p>
            </div>
            <div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
        <div id="modal4" class="modal">
            <div class="modal-content">
                <h4>Name Here</h4>
                <p>{% lorem %}</p>
            </div>
            <div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
        <div id="modal5" class="modal">
            <div class="modal-content">
                <h4>Name Here</h4>
                <p>{% lorem %}</p>
            </div>
            <div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/base.html
{% load staticfiles %}

<!doctype html>
<html>
    <head>
        <title>WC CONSULTANCY {% block title %}{% endblock%}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{% static 'main/materialize/css/materialize.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'main/materialize/css/style.css' %}"  media="screen,projection"/>
    </head>

    <body>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'main/materialize/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'main/materialize/js/init.js' %}"></script>
        <script type="text/javascript" src="{% static 'main/js/zepto/zepto.js' %}"></script>

        {% block page_javascript %}
        {% endblock %}

        {% block site_header %}
          {% include 'components/site_header.html' %}
        {% endblock %}

        {% block main %}{% endblock %}

        {% block footer %}
            {% include 'components/footer.html' %}
        {% endblock %}
    </body>
</html>

main/templates/components/footer.html
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">WC Consultancy</h5>
        <p class="grey-text text-lighten-4">Door 5 Bldg 3, Doña Segunda Complex, Ponciano St., Davao City</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Contact Us!</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" target="_blank" href="https://fb.com/WC-Education-Consultancy-262920817488823/">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
          <li><span class="grey-text text-lighten-3">wceducationconsultancy@gmail.com</span></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2017 Copyright WC Consultancy
    </div>
  </div>
</footer>

main/templates/components/site_header.html
{% load staticfiles %}
<nav class="white" role="navigation">
    <div class="nav-wrapper container white">
      <a href="{% url 'index' %}" class="brand-logo"><img class="responsive-img logo" src="{% static 'main/img/wc-logo2.png' %}"></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'universities' %}">Universities</a></li>
        <li><a href="{% url 'about' %}">About Us</a></li>
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">Sign Up</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
          <li><a href="{% url 'universities' %}">Universities</a></li>
          <li><a href="#">Contact Us</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Sign Up</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons wc-color">menu</i></a>
    </div>
</nav>

main/templates/home/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
<!-- first parallax section -->
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center wc-color">WC Consultancy</h1>
        <div class="row center">
          <h5 class="header col s12 light-grey-text">An International Education Consultancy Firm</h5>
        </div>
        <div class="row center">
          <a href="#" class="btn-large">Get Started</a>
        </div>
        <br><br>
      </div>
    </div>
    <div class="parallax"><img src="{% static 'main/img/rsz_background2.jpg' %}" alt="Unsplashed background img 1"></div>
  </div>
  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center wc-color"><i class="material-icons">spellcheck</i></h2>
            <h5 class="center">Learn</h5>
            <p class="light center">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center wc-color"><i class="material-icons">group</i></h2>
            <h5 class="center">Experience</h5>
            <p class="light center">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center wc-color"><i class="material-icons">mode_edit</i></h2>
            <h5 class="center">Contribute</h5>

            <p class="light center">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- end first parallax section -->

<!-- second parallax section -->
  <div class="parallax-container valign-wrapper">
    <!-- <div class="section no-pad-bot">
      <div class="container">
        <h2 class="row center wc-color">Our Mission</h2>
        <div class="row center">
          <h5 class="header col s12 light-grey-text">An International Education Consultancy Firm</h5>
        </div>
      </div>
    </div> -->
    <div class="parallax"><img src="{% static 'main/img/rsz_background3.jpg' %}" alt="Unsplashed background img 1"></div>
  </div>
  <div class="container">
    <div class="section">
        <div class="row">
            <div class="col s12 m6">
                <div class="icon-block">
                    <h2 class="center wc-color"><i class="material-icons">assignment</i></h2>
                    <h4 class="center">Our Mission</h4>
                    <p class="light center">
                        Our mission is to help leaders of today in learning new skills, conquer new experiences and formulate
                        new ideas that can benefit the world. We believe that attaining international education can be a
                        gateway to achieve personal and international success.
                    </p>
                </div>
            </div>
            <div class="col s12 m6">
                <div class="icon-block">
                    <h2 class="center wc-color"><i class="material-icons">language</i></h2>
                    <h4 class="center">Our Goal</h4>
                    <p class="light center">
                        Advocate for more inclusive access to international education and stimulate a more progressive
                        knowledge economy that benefit the world.
                    </p>
                </div>
            </div>
        </div>
    </div>
  </div>
  <!-- end second parallax section -->
{% endblock %}

main/templates/universities/university.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="container center content">
    {% if universities %}
        <div class="row">
        {% for university in universities %}
            <div class="col s4">
                <div class="card blue-grey darken-1 hoverable">
                    <div class="card-content white-text">
                        <img src="{% static 'main/img/book.jpg' %}" alt="" class="circle responsive-img">
                        <span class="truncate card-title">{{ university.name }}</span>
                        <p class="wc-truncate">{{ university.background }}</p>
                    </div>
                    <div class="card-action">
                      <a class="truncate" href="{{ university.website }}" target="_blank">{{ university.website }}</a>
                    </div>
              </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <i class="small material-icons">info_outline</i><p>Oops! No universities are available for now!</p>
    {% endif %}
    </div>
{% endblock %}

main/templates/universities/university_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="container content">
        <h4>{{ university.name }}</h4>
        <i class="material-icons wc-color middle">room</i>{{ university.state.name }}
        <i class="material-icons wc-color middle">assessment</i>{{ university.acceptance_rate }}%
        <a href="{{ university.website }}" target="_blank">
            <i class="material-icons wc-color middle">http</i>{{ university.website }}
        </a>
        <p>{{ university.background }}</p>
        {% if admissions %}
            <h5> Admission Requirements</h5>
            <ul class="collapsible" data-collapsible="accordion">
                {% for admission in admissions %}
                    <li>
                        <div class="collapsible-header">
                            <i class="material-icons wc-color">info_outline</i>{{ admission.get_program_type_display }} - {{  admission.get_admission_type_display}}
                        </div>
                        <div class="collapsible-body">
                            {% if admission.detail %}
                                <p>{{ admission.detail }}</p>
                            {% endif %}
                            {% for requirement in admission.requirements.all %}
                                <ul class="collection">
                                    <li class="collection-item">
                                        <i class="material-icons wc-color middle">label</i> {{ requirement.detail }}
                                    </li>
                                </ul>
                            {% endfor %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

main/templates/universities/university_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="container center content">
    {% if universities %}
        <div class="row">
        {% for university in universities %}
            <div class="col s4">
                <div class="card large blue-grey darken-1 hoverable university-item">
                    <div class="card-content white-text">
                        <a class="white-text" href="{% url 'university-detail' university.pk %}">
                            {% if university.logo %}
                                <img src="{{ university.logo.url }}" alt="" class="circle responsive-img">
                            {% elif university.logo_link %}
                                <img src="{{ university.logo_link }}" alt="" class="circle responsive-img">
                            {% else %}
                                <img src="{% static 'main/img/book.jpg' %}" alt="" class="circle responsive-img">
                            {% endif %}
                            <span class="truncate card-title">{{ university.name }}</span>
                            <p class="wc-truncate">{{ university.background }}</p>
                        </a>
                    </div>
                    <div class="card-action">
                      {% if university.website %}
                        <a class="truncate" href="{{ university.website }}" target="_blank">{{ university.website }}</a>
                      {% else %}
                        <a href="#">not available</a>
                      {% endif %}
                    </div>
              </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <i class="small material-icons">info_outline</i><p>Oops! No universities are available for now!</p>
    {% endif %}
    {% if universities.has_other_pages %}
        <ul class="pagination">
            {% if universities.has_previous %}
                <li class="waves-effect"><a href="?page={{ universities.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
            {% endif %}
            {% for i in universities.paginator.page_range %}
                {% if universities.number == i %}
                    <li class="active waves-effect"><a href="#">{{ universities.number }}</a></li>
                {% else %}
                    <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if universities.has_next %}
                <li class="waves-effect"><a href="?page={{ universities.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
            {% endif %}
        </ul>
    {% endif %}
    </div>
{% endblock %}
{% block page_javascript %}
    <script type="text/javascript" src="{% static 'main/js/dotdotdot/dotdotdot.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/university/university_list.js' %}"></script>
{% endblock %}